services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    hostname: rabbitmq
    restart: always
    env_file:
      - .env
    volumes:
      - /var/lib/rabbitmq
    ports:
      - 5672:5672
      - 15672:15672

  auth:
    container_name: auth
    build:
      context: ./
      dockerfile: ./apps/auth/Dockerfile
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_ADDR: postgres
      POSTGRES_DB: shadow_hunters
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_URI: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5436/${POSTGRES_DB}?schema=public
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/usr/src/app # any change to base folder should be reflected
      # - /usr/src/app/node_modules
    networks:
      - backend_networks
    command: bun start:dev:auth # overrides CMD from dockerfile

  api:
    container_name: api
    build:
      context: ./
      dockerfile: ./apps/api/Dockerfile
    ports:
      - 4000:5000
    restart: always
    env_file:
     - .env
    depends_on:
      - rabbitmq
      - auth
    volumes:
      - .:/usr/src/app # any change to base folder should be reflected
      # - /usr/src/app/node_modules
    networks:
      - backend_networks
    command: bun start:dev:api # overrides CMD from dockerfile

  postgres:
    container_name: database
    image: postgres:latest
    restart: unless-stopped
    # env_file:
    #   - .env
    ports:
      - 5436:5432
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test:
        ["CMD", "pg_isready", "-U", "root", "-d", "shadow_hunters"]
      interval: 5s
      timeout: 10s
      retries: 5
    networks:
      - backend_networks

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    env_file:
      - .env
    ports:
      - 15432:80
    networks:
      - backend_networks

networks:
  backend_networks:
    driver: bridge

volumes:
  postgres-data: {}
